# Generated by Django 4.1.5 on 2023-01-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('comentario_id', models.IntegerField()),
                ('usuarios_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('porcentaje', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='descuentos_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dto_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='imagenes_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='producto_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='proveedores_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipos_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=45)),
                ('proveedor_estado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.proveedores_estado')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=45)),
                ('caracteristicas', models.TextField(max_length=450)),
                ('precio', models.FloatField()),
                ('cantidad', models.CharField(max_length=45)),
                ('categorias_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.categorias')),
                ('comentarios_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.comentarios')),
                ('descuentos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.descuentos')),
                ('imagenes_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.imagenes')),
                ('marcas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.marcas')),
                ('producto_estado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.producto_estado')),
                ('proveedores_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.proveedores')),
                ('tipos_producto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.tipos_producto')),
            ],
        ),
        migrations.AddField(
            model_name='imagenes',
            name='imagen_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.imagenes_estado'),
        ),
        migrations.AddField(
            model_name='descuentos',
            name='descuento_estado_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.descuentos_estado'),
        ),
    ]
