# Generated by Django 4.1.5 on 2023-01-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='usuario_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('num_documento', models.IntegerField()),
                ('correo', models.CharField(max_length=125)),
                ('contrasena', models.CharField(max_length=16)),
                ('num_contacto', models.IntegerField(max_length=12)),
                ('edad', models.DateField()),
                ('direccion', models.CharField(max_length=45)),
                ('genero_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cliente.generos')),
                ('rol_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cliente.roles')),
                ('tipo_documento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cliente.tipo_documento')),
                ('usuario_estado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cliente.usuario_estado')),
            ],
        ),
    ]
